version: '3'
services:
  db:
    ports:
      - '27017:27017'
  redis:
    ports:
      - '6379:6379'
  next:
    ports:
      - '3000:3000'
  ooth:
    ports:
      - '3001:3001'
  api:
    ports:
      - '3002:3002'
